#!/usr/bin/env bash

set -e

function cleanup_at_exit {
  # remove temporary key file
  rm tmp.pem
}

trap cleanup_at_exit EXIT

# Get the repo name from the `origin` git remote.
export REPO=$(git remote get-url or